version: '3'

services:
  server:
    build: ./
    ports:
      - 4400:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3