defaults: &defaults
  working_directory: ~/repo
  docker:
    # - image: esba-ops/ci-node:latest # uncomment (comment the below) to test a local image
    - image: 458662379798.dkr.ecr.us-west-2.amazonaws.com/esba-ops/ci-node:latest
      aws_auth:
        aws_access_key_id: $ECR_OPS_ACCESS_ID_PROD
        aws_secret_access_key: $ECR_OPS_SECRET_ACCESS_KEY_PROD

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: npm audit

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
              /usr/ci_app/circleci.sh # create config values
              source ~/.bashrc # workaround
              groundhog deploy -a groundhog-testbed -e cloudops-dev-example --s3-bucket elasticbeanstalk-us-west-2-973338787170 --aws-profile default

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
