defaults: &defaults
  working_directory: ~/repo
  docker:
      # - image: circleci/node:latest
      - image: 973338787170.dkr.ecr.us-west-2.amazonaws.com/esba-ops/ci-node:latest
        aws_auth:
          aws_access_key_id: $ECR_OPS_ACCESS_ID_DEV
          aws_secret_access_key: $ECR_OPS_SECRET_ACCESS_KEY_DEV
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: npm audit

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: groundhog deploy -a $CIRCLE_PROJECT_REPONAME -e $CIRCLE_PROJECT_REPONAME
workflows:
  version: 2
  build:
    jobs:
      - build
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
