defaults: &defaults
  shell: /bin/bash --login -eo pipefail
  working_directory: ~/repo
  docker:
    # - image: esba-ops/ci-node:latest # uncomment (comment the below) to test a local image
    # uncomment to test the DEV node instance
    # - image: 496386341798.dkr.ecr.us-west-2.amazonaws.com/esba-ops/ci-node:latest
    - image: 333878251527.dkr.ecr.us-west-2.amazonaws.com/ci_node:latest
      aws_auth:
        aws_access_key_id: $ECR_AWS_ACCESS_KEY_ID
        aws_secret_access_key: $ECR_AWS_SECRET_ACCESS_KEY

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

      - persist_to_workspace:
          root: ~/repo
          paths: .

  audit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm audit

  deploy:
    <<: *defaults
    steps:
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run deploy

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: esba-ops-dev
  build_deploy:
    jobs:
      - build:
          context: esba-ops-dev
      - audit:
          context: esba-ops-dev
          requires:
            - build
      - deploy_approval:
          type: approval
          requires:
            - audit
          filters:
            branches:
              only: master
      - deploy:
          context: esba-ops-dev
          requires:
            - deploy_approval
